SET SQL_SAFE_UPDATES = 0;
delete from aepdev.`aep_context_t3` where ctxjob='dwa_gross_add_ic_caller_daily' and ctxarea='KPI';


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stepcnt',
'5',
'step count'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgqry1',
'
TRUNCATE TABLE ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1
',
'step 1'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgqry2',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1
(
 NO_OF_IC_CALLER
,NO_OF_ALL_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
SUM(GA.NO_OF_DTAC_SUBSCRIBER) as NO_OF_IC_CALLER,
(SUM(GA.NO_OF_DTAC_SUBSCRIBER)
+ SUM(GA.NO_OF_AIS_SUBSCRIBER*RATIO.AIS_GROSS_ADDS_RATIO)
+ SUM(GA.NO_OF_TRUEMOVE_SUBSCRIBER*RATIO.TRUEMOVE_GROSS_ADDS_RATIO))  as NO_OF_ALL_IC_CALLER,
\'Dtac\'   AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
GA.DAY_ID AS REPORT_DATE,
DATE_PART(\'MONTH\', GA.DAY_ID) AS REPORT_MONTH,
DATE_PART(\'YEAR\', GA.DAY_ID) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,     
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID = current_date-1
AND upper(PROVINCE_NAME) NOT IN (\'NATIONWIDE\') 
GROUP BY DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER
UNION ALL
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,     
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID = current_date-1
AND upper(PROVINCE_NAME) IN (\'NATIONWIDE\') 
group by DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER)GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT = \'9999-12-31\'
AND VCM.ACCOUNT_TYPE_CD = 0
GROUP BY GA.DAY_ID,VCM.AMPHUR_CD,VCM.TAMBON_CD,VCM.PROVINCE_CD
',
'step 2'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgqry3',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1
(
 NO_OF_IC_CALLER
,NO_OF_ALL_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
SUM(GA.NO_OF_AIS_SUBSCRIBER*RATIO.AIS_GROSS_ADDS_RATIO) as NO_OF_IC_CALLER,
(SUM(GA.NO_OF_DTAC_SUBSCRIBER)
+ SUM(GA.NO_OF_AIS_SUBSCRIBER*RATIO.AIS_GROSS_ADDS_RATIO)
+ SUM(GA.NO_OF_TRUEMOVE_SUBSCRIBER*RATIO.TRUEMOVE_GROSS_ADDS_RATIO)) as NO_OF_ALL_IC_CALLER,
\'AIS\' AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
GA.DAY_ID AS REPORT_DATE,
DATE_PART(\'MONTH\', GA.DAY_ID) AS REPORT_MONTH,
DATE_PART(\'YEAR\', GA.DAY_ID) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID = current_date-1
AND upper(PROVINCE_NAME) NOT IN (\'NATIONWIDE\')  
GROUP BY DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER
UNION ALL
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID = current_date-1
AND upper(PROVINCE_NAME) IN (\'NATIONWIDE\') 
GROUP BY DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER)GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT = \'9999-12-31\'
AND VCM.ACCOUNT_TYPE_CD = 0
GROUP BY GA.DAY_ID,VCM.AMPHUR_CD,VCM.TAMBON_CD,VCM.PROVINCE_CD
',
'step 3'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgqry4',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1
(
 NO_OF_IC_CALLER
,NO_OF_ALL_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
SUM(GA.NO_OF_TRUEMOVE_SUBSCRIBER*RATIO.TRUEMOVE_GROSS_ADDS_RATIO) as NO_OF_IC_CALLER,
(SUM(GA.NO_OF_DTAC_SUBSCRIBER)
+ SUM(GA.NO_OF_AIS_SUBSCRIBER*RATIO.AIS_GROSS_ADDS_RATIO)
+ SUM(GA.NO_OF_TRUEMOVE_SUBSCRIBER*RATIO.TRUEMOVE_GROSS_ADDS_RATIO)) as NO_OF_ALL_IC_CALLER,
\'TRUE\' AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
GA.DAY_ID AS REPORT_DATE,
DATE_PART(\'MONTH\', GA.DAY_ID) AS REPORT_MONTH,
DATE_PART(\'YEAR\', GA.DAY_ID) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID = current_date-1
AND upper(PROVINCE_NAME) IN (\'NATIONWIDE\') 
GROUP BY DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER
union
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID = current_date-1
AND upper(PROVINCE_NAME) not IN (\'NATIONWIDE\') 
GROUP BY DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER)GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT = \'9999-12-31\'
AND VCM.ACCOUNT_TYPE_CD = 0
GROUP BY GA.DAY_ID,VCM.AMPHUR_CD,VCM.TAMBON_CD,VCM.PROVINCE_CD
',
'step 4'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgqry5',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_DAILY
SELECT
 NO_OF_IC_CALLER
,NO_OF_ALL_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
FROM ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1
',
'step 5'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgtable1',
'~SCHEMAVA~.dwa_gross_add_ic_caller_daily_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgtable2',
'~SCHEMAVA~.dwa_gross_add_ic_caller_daily_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgtable3',
'~SCHEMAVA~.dwa_gross_add_ic_caller_daily_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgtable4',
'~SCHEMAVA~.dwa_gross_add_ic_caller_daily_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'dwa_gross_add_ic_caller_daily',
'stgtable5',
'~SCHEMAVA~.dwa_gross_add_ic_caller_daily',
null
);

