SET SQL_SAFE_UPDATES = 0;
delete from aepdev.`aep_context_t3` where ctxjob='DWA_GROSS_ADD_IC_CALLER_MTD' and ctxarea='KPI';


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stepcnt',
'6',
'step count'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgqry1',
'
TRUNCATE TABLE ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_STG1
',
'step 1'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgqry2',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_STG1
(
 NO_OF_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
GA.NO_OF_IC_CALLER,
 \'Dtac \'   AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
LAST_DAY(GA.DAY_ID) AS REPORT_DATE,
DATE_PART( \'MONTH \', LAST_DAY(GA.DAY_ID)) AS REPORT_MONTH,
DATE_PART( \'YEAR \', LAST_DAY(GA.DAY_ID)) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'AIS \' AS OPERATOR_NAME,     
SUM(NO_OF_DTAC_SUBSCRIBER) as NO_OF_IC_CALLER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) IN ( \'NATIONWIDE \') 
AND NO_OF_DTAC_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME)
UNION
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'AIS \' AS OPERATOR_NAME,     
SUM(NO_OF_DTAC_SUBSCRIBER) as NO_OF_IC_CALLER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) not IN ( \'NATIONWIDE \') 
AND NO_OF_DTAC_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME))GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT =  \'9999-12-31 \'
AND VCM.ACCOUNT_TYPE_CD = 0
',
'step 2'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgqry3',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_STG1
(
 NO_OF_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
SUM(GA.NO_OF_AIS_SUBSCRIBER*RATIO.AIS_GROSS_ADDS_RATIO) AS NO_OF_IC_CALLER,
 \'AIS \' AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
LAST_DAY(GA.DAY_ID) AS REPORT_DATE,
DATE_PART( \'MONTH \', LAST_DAY(GA.DAY_ID)) AS REPORT_MONTH,
DATE_PART( \'YEAR \', LAST_DAY(GA.DAY_ID)) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'AIS \' AS OPERATOR_NAME,     
NO_OF_AIS_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) IN ( \'NATIONWIDE \') 
AND NO_OF_AIS_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_AIS_SUBSCRIBER)
UNION
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'AIS \' AS OPERATOR_NAME,     
NO_OF_AIS_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) not IN ( \'NATIONWIDE \') 
AND NO_OF_AIS_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_AIS_SUBSCRIBER))GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT =  \'9999-12-31 \'
AND VCM.ACCOUNT_TYPE_CD = 0
group by GA.DAY_ID,VCM.AMPHUR_CD,VCM.TAMBON_CD,VCM.PROVINCE_CD
',
'step 3'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgqry4',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_STG1
(
 NO_OF_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
SUM(GA.NO_OF_TRUEMOVE_SUBSCRIBER*RATIO.TRUEMOVE_GROSS_ADDS_RATIO) AS NO_OF_IC_CALLER,
 \'TRUE \' AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
LAST_DAY(GA.DAY_ID) AS REPORT_DATE,
DATE_PART( \'MONTH \', LAST_DAY(GA.DAY_ID)) AS REPORT_MONTH,
DATE_PART( \'YEAR \', LAST_DAY(GA.DAY_ID)) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'TRUE \' AS OPERATOR_NAME,     
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) IN ( \'NATIONWIDE \') 
AND NO_OF_TRUEMOVE_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_TRUEMOVE_SUBSCRIBER)
UNION
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'TRUE \' AS OPERATOR_NAME,     
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) not IN ( \'NATIONWIDE \') 
AND NO_OF_TRUEMOVE_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_TRUEMOVE_SUBSCRIBER))GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT =  \'9999-12-31 \'
AND VCM.ACCOUNT_TYPE_CD = 0
GROUP BY GA.DAY_ID,VCM.AMPHUR_CD,VCM.TAMBON_CD,VCM.PROVINCE_CD
',
'step 4'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgqry5',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_STG1
(
 NO_OF_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
)
SELECT 
(SUM(GA.NO_OF_DTAC_SUBSCRIBER)  + SUM(GA.NO_OF_AIS_SUBSCRIBER*RATIO.AIS_GROSS_ADDS_RATIO) + SUM(GA.NO_OF_TRUEMOVE_SUBSCRIBER*RATIO.TRUEMOVE_GROSS_ADDS_RATIO)) AS NO_OF_IC_CALLER,
 \'ALL \' AS IC_OPERATOR,
VCM.AMPHUR_CD AS MOST_USED_AMPHUR_CODE,
VCM.TAMBON_CD AS MOST_USED_TUMBON_CODE,
VCM.PROVINCE_CD AS MOST_USED_PROVINCE_CODE,
null AS PROCESS_NAME,
~EXECUTIONID~               AS EXECUTION_ID,
LAST_DAY(GA.DAY_ID) AS REPORT_DATE,
DATE_PART( \'MONTH \', LAST_DAY(GA.DAY_ID)) AS REPORT_MONTH,
DATE_PART( \'YEAR \', LAST_DAY(GA.DAY_ID)) AS REPORT_YEAR,
\'~LOADUSER~\'              AS LOAD_USER,
\'~LOADDATE~\'              AS LOAD_DATE,
\'~DWLASTUPDATETIME~\' AS DW_LAST_UPDATE_TIME
FROM
(SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'ALL \' AS OPERATOR_NAME,     
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) IN ( \'NATIONWIDE \') 
AND NO_OF_TRUEMOVE_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER)
UNION
SELECT     
DAY_ID ,
TAMBON_CD,
AMPHUR_NAME,
PROVINCE_NAME,
 \'ALL \' AS OPERATOR_NAME,     
NO_OF_DTAC_SUBSCRIBER,
NO_OF_AIS_SUBSCRIBER,
NO_OF_TRUEMOVE_SUBSCRIBER
FROM ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_GROSSADD_TAMBON_DAILY
WHERE  DAY_ID  BETWEEN (DATE_TRUNC( \'MONTH \', DAY_ID::TIMESTAMP)::DATE) and getdate()
AND upper(PROVINCE_NAME) not IN ( \'NATIONWIDE \') 
AND NO_OF_TRUEMOVE_SUBSCRIBER > 0 
GROUP BY 
ROLLUP(DAY_ID ,TAMBON_CD,AMPHUR_NAME,PROVINCE_NAME,NO_OF_DTAC_SUBSCRIBER,NO_OF_AIS_SUBSCRIBER,NO_OF_TRUEMOVE_SUBSCRIBER))GA
INNER JOIN ~SCHEMAVA~.USAGE_INTERCONNECT_CALLER_RATIO_DAILY AS RATIO
ON GA.DAY_ID = RATIO.DAY_ID 
LEFT OUTER JOIN ~SCHEMAVA~.DIM_CLUSTER AS VCM
ON GA.PROVINCE_NAME = VCM.PROVINCE_EN
AND GA.AMPHUR_NAME  = VCM.AMPHUR_EN
AND GA.TAMBON_CD = VCM.TAMBON_EN
WHERE VCM.REC_END_DT =  \ \'9999-12-31 \'
AND VCM.ACCOUNT_TYPE_CD = 0
GROUP BY GA.DAY_ID,VCM.AMPHUR_CD,VCM.TAMBON_CD,VCM.PROVINCE_CD
',
'step 5'
);

insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgqry6',
'
INSERT INTO ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD
SELECT
 NO_OF_IC_CALLER
,IC_OPERATOR
,MOST_USED_AMPHUR_CODE
,MOST_USED_TUMBON_CODE
,MOST_USED_PROVINCE_CODE
,PROCESS_NAME
,EXECUTION_ID
,REPORT_DATE
,REPORT_MONTH
,REPORT_YEAR
,LOAD_USER
,LOAD_DATE 
,DW_LAST_UPDATE_TIME
FROM ~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_STG1
',
'step 6'
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgtable1',
'~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgtable2',
'~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgtable3',
'~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgtable4',
'~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_stg1',
null
);


insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgtable5',
'~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD_stg1',
null
);

insert into aepdev.`aep_context_t3` ( `region` , `ctxarea` , `ctxjob` , `ctxkey` , `ctxval` , `remarks` )
values
(
'BKK',
'KPI',
'DWA_GROSS_ADD_IC_CALLER_MTD',
'stgtable6',
'~SCHEMAVA~.DWA_GROSS_ADD_IC_CALLER_MTD',
null
);

