DROP TABLE IF EXISTS DTDVTA.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1;
DROP TABLE IF EXISTS DTDVTA.DWA_GROSS_ADD_IC_CALLER_DAILY;

/*STEP 1*/
/*CREATE STAGE TABLE*/


CREATE TABLE IF NOT EXISTS DTDVTA.DWA_GROSS_ADD_IC_CALLER_DAILY_STG1	
(
 NO_OF_IC_CALLER  INT
,NO_OF_ALL_IC_CALLER INT
,IC_OPERATOR  VARCHAR(10)
,MOST_USED_AMPHUR_CODE  VARCHAR(50)
,MOST_USED_TUMBON_CODE  VARCHAR(50)
,MOST_USED_PROVINCE_CODE  VARCHAR(50)
,PROCESS_NAME VARCHAR(200)
,EXECUTION_ID BIGINT
,REPORT_DATE VARCHAR(20)  not null
,REPORT_MONTH  VARCHAR(10)
,REPORT_YEAR  VARCHAR(10)
,LOAD_USER VARCHAR(100)
,LOAD_DATE TIMESTAMP
,DW_LAST_UPDATE_TIME TIMESTAMP
);

/*STEP 2*/
/*CREATE TARGET TABLE*/

CREATE TABLE IF NOT EXISTS DTDVTA.DWA_GROSS_ADD_IC_CALLER_DAILY
(
 NO_OF_IC_CALLER  INT
,NO_OF_ALL_IC_CALLER INT
,IC_OPERATOR  VARCHAR(10)
,MOST_USED_AMPHUR_CODE  VARCHAR(50)
,MOST_USED_TUMBON_CODE  VARCHAR(50)
,MOST_USED_PROVINCE_CODE  VARCHAR(50)
,PROCESS_NAME VARCHAR(200)
,EXECUTION_ID BIGINT
,REPORT_DATE VARCHAR(20)  not null
,REPORT_MONTH  VARCHAR(10)
,REPORT_YEAR  VARCHAR(10)
,LOAD_USER VARCHAR(100)
,LOAD_DATE TIMESTAMP
,DW_LAST_UPDATE_TIME TIMESTAMP
)
PARTITION BY (DTDVTA.DWA_GROSS_ADD_IC_CALLER_DAILY.REPORT_DATE);